### ISSUE TITLE
Rooms are still displayed after changing the config file

### ISSUE THREAD

**Issue by AnddyAnddy** [morko/haxroomie#62] opened 2019-08-13 10:20 UTC
using haxroomie, i opened 2 rooms, room1 and room2
after that, i modified the config file to add 2 other rooms (with a slightly different config), room3 and room4, and i also changed the name of room1 and room2 to fs1 and fs2

after that, i went back to haxroomie and i did a reload and I saw the 6 rooms instead of only 4
to fix this, I just left haxroomie using q and i re-opened it and it worked as I expected

**Comment by morko** [comment] 2019-08-14 13:28
I cannot reproduce the bug. :/ Could you give me your config (without the passwords) that caused this to happen?

**Comment by morko** [comment] 2019-12-04 09:26
Closing this because did not get enough information and could not reproduce. Maybe it got fixed in some commit already.

**Closed as completed by morko** 2019-12-04 09:26 UTC
Labels: bug
